# Generated by Django 4.2.3 on 2023-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moto',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
    ]
